name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  multiarch:
    uses: poseidon/fleetlock/.github/workflows/multiarch.yaml@main
    secrets:
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
